language: ruby
rvm:
- 2.2.7
- 2.3.4
- 2.4.1
script: bundle exec rspec
after_success: bundle exec codeclimate-test-reporter
notifications:
  email: false
addons:
  code_climate:
    repo_token:
      secure: dsEtF8xLeOgJRvUDJWvegIgPaRPaaSd63RjXOZ/mHnhupv4GxseN6itvZPeNNNTOD7H6HvXzsqKYBhszqUVJypg6c5jcgoOOcjOppMFYJioXe8Du8UWgNIEP0rLCkVIacXxVg1Eqq3kqKBBGKlf42nt7jXWt6/+UnxEJaqSSRzg=
